# Generated by Django 5.2.5 on 2025-08-21 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_key',
            field=models.CharField(blank=True, editable=False, help_text='Clé serveur secrète générée automatiquement.', max_length=64, null=True, unique=True),
        ),
    ]
