# Generated by Django 5.2.5 on 2025-08-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='alt',
            field=models.CharField(blank=True, help_text='Alt pour l’accessibilité.', max_length=160, verbose_name='Texte alternatif (alt)'),
        ),
        migrations.AddField(
            model_name='offer',
            name='btnLabel',
            field=models.CharField(blank=True, help_text='Libellé du bouton (ex: “Choisir”).', max_length=60),
        ),
        migrations.AddField(
            model_name='offer',
            name='category',
            field=models.CharField(choices=[('solo', 'Solo'), ('duo', 'Duo'), ('famille', 'Famille')], default='solo', help_text='Catégorie front (solo / duo / famille).', max_length=16),
        ),
        migrations.AddField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, help_text='Image 900×1025 px.', null=True, upload_to='offres/'),
        ),
        migrations.AddField(
            model_name='offer',
            name='titre',
            field=models.CharField(blank=True, help_text='Titre affiché (défaut = name).', max_length=120),
        ),
        migrations.AlterField(
            model_name='offer',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, unique=True),
        ),
    ]
