# Generated by Django 5.2.5 on 2025-09-05 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_offer_alt_offer_btnlabel_offer_category_offer_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, help_text='Image 900×1225 px.', null=True, upload_to='offres/'),
        ),
    ]
